import type { SourceSchema } from "@/lib/types";

export const STRIPE_SCHEMA: SourceSchema = {
  source: "stripe",
  label: "Stripe Payments",
  fields: [
    {
      key: "external_payment_id",
      label: "Payment ID",
      type: "text",
      required: true,
      aliases: [
        "stripe_payment_id",
        "id",
        "payment_id",
        "charge_id",
        "payment id",
        "charge id",
        "stripe id",
        "transaction id",
        "transaction_id",
      ],
      samplePattern: /^(pi_|ch_|in_)/,
      description: "Stripe payment or charge ID (e.g. pi_xxx, ch_xxx)",
    },
    {
      key: "customer_email",
      label: "Customer Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "customer email",
        "customer_email",
        "receipt email",
        "receipt_email",
        "billing email",
      ],
      description: "Customer email address",
    },
    {
      key: "customer_name",
      label: "Customer Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "name",
        "customer name",
        "customer_name",
        "billing name",
        "billing_name",
        "cardholder name",
      ],
      description: "Customer full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Customer phone number",
    },
    {
      key: "amount",
      label: "Amount",
      type: "currency",
      required: true,
      aliases: [
        "amount",
        "total",
        "charge amount",
        "payment amount",
        "amount (usd)",
        "converted amount",
      ],
      description: "Payment amount (numeric, may include $ or commas)",
    },
    {
      key: "currency",
      label: "Currency",
      type: "text",
      required: false,
      aliases: [
        "currency",
        "currency code",
        "payment currency",
        "converted currency",
      ],
      description: "ISO currency code (e.g. USD, EUR)",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: ["status", "payment status", "charge status", "outcome"],
      enumValues: ["succeeded", "pending", "failed", "refunded"],
      description: "Payment status",
    },
    {
      key: "customer_external_id",
      label: "Customer ID",
      type: "text",
      required: false,
      aliases: [
        "stripe_customer_id",
        "customer_id",
        "customer id",
        "cus_id",
        "stripe customer id",
      ],
      samplePattern: /^cus_/,
      description: "Stripe customer ID (e.g. cus_xxx)",
    },
    {
      key: "payment_date",
      label: "Payment Date",
      type: "timestamp",
      required: true,
      aliases: [
        "created",
        "created (utc)",
        "date",
        "payment date",
        "payment_date",
        "created_at",
        "created at",
        "timestamp",
        "paid at",
        "charge date",
      ],
      description: "When the payment was created",
    },
  ],
  idField: "external_payment_id",
  emailField: "customer_email",
  nameField: "customer_name",
  phoneField: "phone",
  customerIdField: "customer_external_id",
};

export const CALENDLY_SCHEMA: SourceSchema = {
  source: "calendly",
  label: "Calendly Bookings",
  fields: [
    {
      key: "external_booking_id",
      label: "Event ID",
      type: "text",
      required: true,
      aliases: [
        "calendly_event_id",
        "event uri",
        "event_uri",
        "event id",
        "event_id",
        "uri",
        "calendly id",
        "booking id",
        "invitee uri",
      ],
      description: "Calendly event URI or ID",
    },
    {
      key: "invitee_id",
      label: "Invitee ID",
      type: "text",
      required: false,
      aliases: [
        "calendly_invitee_id",
        "invitee_id",
        "invitee id",
      ],
      description: "Calendly invitee ID",
    },
    {
      key: "invitee_email",
      label: "Invitee Email",
      type: "email",
      required: false,
      aliases: [
        "invitee email",
        "invitee_email",
        "email",
        "guest email",
        "attendee email",
        "invitee e-mail",
      ],
      description: "Invitee email address",
    },
    {
      key: "invitee_name",
      label: "Invitee Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "invitee name",
        "invitee_name",
        "name",
        "guest name",
        "attendee name",
        "invitee full name",
      ],
      description: "Invitee full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Invitee phone number",
    },
    {
      key: "event_type",
      label: "Event Type",
      type: "text",
      required: false,
      aliases: [
        "service_name",
        "event type",
        "event_type",
        "event type name",
        "meeting type",
        "type",
        "appointment type",
      ],
      description: "Type of meeting/event",
    },
    {
      key: "start_time",
      label: "Start Time",
      type: "timestamp",
      required: true,
      aliases: [
        "booking_date",
        "start date & time",
        "start date and time",
        "start_time",
        "start time",
        "scheduled time",
        "start",
        "event date",
        "date",
        "meeting start",
      ],
      description: "Scheduled start time",
    },
    {
      key: "end_time",
      label: "End Time",
      type: "timestamp",
      required: false,
      aliases: [
        "end date & time",
        "end date and time",
        "end_time",
        "end time",
        "end",
        "meeting end",
      ],
      description: "Scheduled end time",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: [
        "status",
        "event status",
        "booking status",
        "canceled",
        "cancelled",
      ],
      enumValues: ["scheduled", "completed", "cancelled", "no_show", "confirmed", "rescheduled"],
      description: "Booking status",
    },
  ],
  idField: "external_booking_id",
  emailField: "invitee_email",
  nameField: "invitee_name",
  phoneField: "phone",
};

export const PASSLINE_SCHEMA: SourceSchema = {
  source: "passline",
  label: "PassLine Attendance",
  fields: [
    {
      key: "external_attendance_id",
      label: "Ticket ID",
      type: "text",
      required: true,
      aliases: [
        "passline_id",
        "ticket id",
        "ticket_id",
        "id",
        "pass id",
        "pass_id",
        "barcode",
        "entry id",
        "check-in id",
        "checkin id",
      ],
      description: "PassLine ticket or entry ID",
    },
    {
      key: "attendee_email",
      label: "Attendee Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "attendee email",
        "attendee_email",
        "guest email",
        "e-mail",
        "contact email",
      ],
      description: "Attendee email address",
    },
    {
      key: "attendee_name",
      label: "Attendee Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "name",
        "full name",
        "attendee name",
        "attendee_name",
        "guest name",
        "visitor name",
        "first name",
      ],
      description: "Attendee full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Attendee phone number",
    },
    {
      key: "event_name",
      label: "Event Name",
      type: "text",
      required: false,
      aliases: [
        "event",
        "event name",
        "event_name",
        "event title",
        "event_title",
        "class",
        "class name",
        "session",
      ],
      description: "Name of the event or class",
    },
    {
      key: "check_in_time",
      label: "Check-in Time",
      type: "timestamp",
      required: true,
      aliases: [
        "check_in_date",
        "checked in at",
        "checked_in_at",
        "check-in time",
        "check_in_time",
        "checkin time",
        "check in",
        "scan time",
        "entry time",
        "arrival time",
        "timestamp",
        "date",
      ],
      description: "When the attendee checked in",
    },
    {
      key: "ticket_type",
      label: "Ticket Type",
      type: "text",
      required: false,
      aliases: [
        "ticket_type",
        "ticket type",
        "pass type",
        "pass_type",
        "entry type",
      ],
      description: "Type of ticket or pass",
    },
  ],
  idField: "external_attendance_id",
  emailField: "attendee_email",
  nameField: "attendee_name",
  phoneField: "phone",
};

export const POS_SCHEMA: SourceSchema = {
  source: "pos",
  label: "POS Transactions",
  fields: [
    {
      key: "external_payment_id",
      label: "Transaction ID",
      type: "text",
      required: true,
      aliases: [
        "pos_transaction_id",
        "transaction_id",
        "transaction id",
        "receipt id",
        "receipt_id",
      ],
      description: "POS transaction ID",
    },
    {
      key: "membership_id",
      label: "Membership ID",
      type: "text",
      required: false,
      aliases: [
        "membership_id",
        "membership id",
        "member_id",
        "member id",
        "customer_id",
      ],
      description: "Customer membership or loyalty ID",
    },
    {
      key: "customer_email",
      label: "Email",
      type: "email",
      required: false,
      aliases: [
        "member_email",
        "email",
        "customer_email",
        "customer email",
      ],
      description: "Customer email address",
    },
    {
      key: "customer_phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: [
        "member_phone",
        "phone",
        "customer_phone",
        "customer phone",
        "mobile",
      ],
      description: "Customer phone number",
    },
    {
      key: "location",
      label: "Location",
      type: "text",
      required: false,
      aliases: [
        "location",
        "store",
        "store_name",
        "store name",
        "branch",
      ],
      description: "Store or location name",
    },
    {
      key: "payment_type",
      label: "Payment Type",
      type: "text",
      required: false,
      aliases: [
        "transaction_type",
        "transaction type",
        "payment_type",
        "payment type",
        "method",
        "payment_method",
      ],
      description: "Type of transaction (e.g. credit, debit, cash)",
    },
    {
      key: "amount",
      label: "Amount",
      type: "currency",
      required: true,
      aliases: [
        "amount",
        "total",
        "transaction_amount",
        "transaction amount",
        "sale amount",
      ],
      description: "Transaction amount",
    },
    {
      key: "currency",
      label: "Currency",
      type: "text",
      required: false,
      aliases: [
        "currency",
        "currency_code",
        "currency code",
      ],
      description: "ISO currency code",
    },
    {
      key: "payment_date",
      label: "Transaction Date",
      type: "timestamp",
      required: true,
      aliases: [
        "transaction_date",
        "transaction date",
        "date",
        "payment_date",
        "payment date",
        "sale date",
        "sale_date",
      ],
      description: "When the transaction occurred",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: ["status", "transaction_status", "transaction status"],
      enumValues: ["approved", "succeeded", "pending", "failed", "refunded", "void"],
      description: "Transaction status",
    },
  ],
  idField: "external_payment_id",
  emailField: "customer_email",
  nameField: "",
  customerIdField: "membership_id",
  phoneField: "customer_phone",
};

export const WETRAVEL_SCHEMA: SourceSchema = {
  source: "wetravel",
  label: "WeTravel Bookings",
  fields: [
    {
      key: "external_booking_id",
      label: "Booking ID",
      type: "text",
      required: true,
      aliases: [
        "booking_id",
        "booking id",
        "reservation_id",
        "reservation id",
      ],
      description: "WeTravel booking ID",
    },
    {
      key: "participant_name",
      label: "Participant Name",
      type: "text",
      required: false,
      aliases: [
        "participant_name",
        "participant name",
        "name",
        "full_name",
        "full name",
        "traveler name",
        "traveler_name",
      ],
      description: "Participant full name",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "participant_email",
        "participant email",
        "contact_email",
      ],
      description: "Participant email address",
    },
    {
      key: "country",
      label: "Country",
      type: "text",
      required: false,
      aliases: [
        "country",
        "nationality",
        "country_code",
        "country code",
      ],
      description: "Participant country",
    },
    {
      key: "trip_name",
      label: "Trip Name",
      type: "text",
      required: false,
      aliases: [
        "trip_name",
        "trip name",
        "tour name",
        "tour_name",
        "event",
        "experience",
      ],
      description: "Name of the trip or tour",
    },
    {
      key: "total_trip_price",
      label: "Total Trip Price",
      type: "currency",
      required: false,
      aliases: [
        "total_trip_price",
        "total trip price",
        "trip_price",
        "trip price",
        "total_price",
        "total price",
      ],
      description: "Total price for the trip",
    },
    {
      key: "amount_paid",
      label: "Amount Paid",
      type: "currency",
      required: false,
      aliases: [
        "amount_paid",
        "amount paid",
        "paid",
        "amount",
        "payment_amount",
      ],
      description: "Amount paid so far",
    },
    {
      key: "remaining_balance",
      label: "Remaining Balance",
      type: "currency",
      required: false,
      aliases: [
        "remaining_balance",
        "remaining balance",
        "balance",
        "balance_due",
        "balance due",
      ],
      description: "Remaining balance to be paid",
    },
    {
      key: "payment_plan_type",
      label: "Payment Plan Type",
      type: "text",
      required: false,
      aliases: [
        "payment_plan_type",
        "payment plan type",
        "payment_plan",
        "payment plan",
        "plan_type",
      ],
      description: "Type of payment plan",
    },
    {
      key: "booking_date",
      label: "Booking Date",
      type: "timestamp",
      required: true,
      aliases: [
        "booking_date",
        "booking date",
        "booked_at",
        "booked at",
        "date",
        "reservation_date",
      ],
      description: "When the booking was made",
    },
    {
      key: "trip_start_date",
      label: "Trip Start Date",
      type: "date",
      required: false,
      aliases: [
        "trip_start_date",
        "trip start date",
        "start_date",
        "start date",
        "departure_date",
        "departure date",
      ],
      description: "Trip start date",
    },
    {
      key: "trip_end_date",
      label: "Trip End Date",
      type: "date",
      required: false,
      aliases: [
        "trip_end_date",
        "trip end date",
        "end_date",
        "end date",
        "return_date",
        "return date",
      ],
      description: "Trip end date",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: [
        "status",
        "booking_status",
        "booking status",
      ],
      enumValues: ["confirmed", "cancelled", "pending", "completed"],
      description: "Booking status",
    },
    {
      key: "refund_amount",
      label: "Refund Amount",
      type: "currency",
      required: false,
      aliases: [
        "refund_amount",
        "refund amount",
        "refund",
        "refunded_amount",
      ],
      description: "Amount refunded",
    },
    {
      key: "lead_source_channel",
      label: "Lead Source Channel",
      type: "text",
      required: false,
      aliases: ["lead_source_channel", "lead source channel", "source_channel", "channel"],
      description: "Marketing channel source",
    },
    {
      key: "utm_source",
      label: "UTM Source",
      type: "text",
      required: false,
      aliases: ["utm_source", "utm source"],
      description: "UTM source parameter",
    },
    {
      key: "utm_medium",
      label: "UTM Medium",
      type: "text",
      required: false,
      aliases: ["utm_medium", "utm medium"],
      description: "UTM medium parameter",
    },
    {
      key: "utm_campaign",
      label: "UTM Campaign",
      type: "text",
      required: false,
      aliases: ["utm_campaign", "utm campaign"],
      description: "UTM campaign parameter",
    },
    {
      key: "utm_content",
      label: "UTM Content",
      type: "text",
      required: false,
      aliases: ["utm_content", "utm content"],
      description: "UTM content parameter",
    },
    {
      key: "referrer",
      label: "Referrer",
      type: "text",
      required: false,
      aliases: ["referrer", "referral_url", "referral url", "referred_by"],
      description: "Referrer URL or source",
    },
    {
      key: "referral_partner",
      label: "Referral Partner",
      type: "text",
      required: false,
      aliases: ["referral_partner", "referral partner", "partner", "affiliate"],
      description: "Referral partner name",
    },
    {
      key: "lead_capture_method",
      label: "Lead Capture Method",
      type: "text",
      required: false,
      aliases: ["lead_capture_method", "lead capture method", "capture_method"],
      description: "How the lead was captured",
    },
  ],
  idField: "external_booking_id",
  emailField: "email",
  nameField: "participant_name",
};

export const SCHEMAS: Record<string, SourceSchema> = {
  stripe: STRIPE_SCHEMA,
  calendly: CALENDLY_SCHEMA,
  passline: PASSLINE_SCHEMA,
  pos: POS_SCHEMA,
  wetravel: WETRAVEL_SCHEMA,
};

export function getSchema(source: string): SourceSchema | undefined {
  return SCHEMAS[source];
}
