import type { SourceSchema } from "@/lib/types";

export const STRIPE_SCHEMA: SourceSchema = {
  source: "stripe",
  label: "Stripe Payments",
  fields: [
    {
      key: "stripe_payment_id",
      label: "Payment ID",
      type: "text",
      required: true,
      aliases: [
        "id",
        "payment_id",
        "charge_id",
        "payment id",
        "charge id",
        "stripe id",
        "transaction id",
        "transaction_id",
      ],
      samplePattern: /^(pi_|ch_|in_)/,
      description: "Stripe payment or charge ID (e.g. pi_xxx, ch_xxx)",
    },
    {
      key: "stripe_customer_id",
      label: "Customer ID",
      type: "text",
      required: false,
      aliases: [
        "customer",
        "customer_id",
        "customer id",
        "stripe customer",
        "stripe customer id",
        "cus id",
      ],
      samplePattern: /^cus_/,
      description: "Stripe customer ID (e.g. cus_xxx)",
    },
    {
      key: "customer_email",
      label: "Customer Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "customer email",
        "customer_email",
        "receipt email",
        "receipt_email",
        "billing email",
      ],
      description: "Customer email address",
    },
    {
      key: "customer_name",
      label: "Customer Name",
      type: "text",
      required: false,
      aliases: [
        "name",
        "customer name",
        "customer_name",
        "billing name",
        "billing_name",
        "cardholder name",
      ],
      description: "Customer full name",
    },
    {
      key: "amount",
      label: "Amount",
      type: "currency",
      required: true,
      aliases: [
        "amount",
        "total",
        "charge amount",
        "payment amount",
        "amount (usd)",
        "converted amount",
      ],
      description: "Payment amount (numeric, may include $ or commas)",
    },
    {
      key: "currency",
      label: "Currency",
      type: "text",
      required: false,
      aliases: [
        "currency",
        "currency code",
        "payment currency",
        "converted currency",
      ],
      description: "ISO currency code (e.g. USD, EUR)",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: ["status", "payment status", "charge status", "outcome"],
      enumValues: ["succeeded", "pending", "failed", "refunded"],
      description: "Payment status",
    },
    {
      key: "payment_date",
      label: "Payment Date",
      type: "timestamp",
      required: true,
      aliases: [
        "created",
        "created (utc)",
        "date",
        "payment date",
        "created_at",
        "created at",
        "timestamp",
        "paid at",
        "charge date",
      ],
      description: "When the payment was created",
    },
    {
      key: "description",
      label: "Description",
      type: "text",
      required: false,
      aliases: [
        "description",
        "memo",
        "statement descriptor",
        "statement_descriptor",
        "notes",
      ],
      description: "Payment description or memo",
    },
  ],
  idField: "stripe_payment_id",
  emailField: "customer_email",
  nameField: "customer_name",
};

export const CALENDLY_SCHEMA: SourceSchema = {
  source: "calendly",
  label: "Calendly Bookings",
  fields: [
    {
      key: "calendly_event_id",
      label: "Event ID",
      type: "text",
      required: true,
      aliases: [
        "event uri",
        "event_uri",
        "event id",
        "event_id",
        "uri",
        "calendly id",
        "booking id",
        "invitee uri",
      ],
      description: "Calendly event URI or ID",
    },
    {
      key: "invitee_email",
      label: "Invitee Email",
      type: "email",
      required: false,
      aliases: [
        "invitee email",
        "invitee_email",
        "email",
        "guest email",
        "attendee email",
        "invitee e-mail",
      ],
      description: "Invitee email address",
    },
    {
      key: "invitee_name",
      label: "Invitee Name",
      type: "text",
      required: false,
      aliases: [
        "invitee name",
        "invitee_name",
        "name",
        "guest name",
        "attendee name",
        "invitee full name",
      ],
      description: "Invitee full name",
    },
    {
      key: "event_type",
      label: "Event Type",
      type: "text",
      required: false,
      aliases: [
        "event type",
        "event_type",
        "event type name",
        "meeting type",
        "type",
        "appointment type",
      ],
      description: "Type of meeting/event",
    },
    {
      key: "start_time",
      label: "Start Time",
      type: "timestamp",
      required: true,
      aliases: [
        "start date & time",
        "start date and time",
        "start_time",
        "start time",
        "scheduled time",
        "start",
        "event date",
        "date",
        "meeting start",
      ],
      description: "Scheduled start time",
    },
    {
      key: "end_time",
      label: "End Time",
      type: "timestamp",
      required: false,
      aliases: [
        "end date & time",
        "end date and time",
        "end_time",
        "end time",
        "end",
        "meeting end",
      ],
      description: "Scheduled end time",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: [
        "status",
        "event status",
        "booking status",
        "canceled",
        "cancelled",
      ],
      enumValues: ["scheduled", "completed", "cancelled", "no_show"],
      description: "Booking status",
    },
  ],
  idField: "calendly_event_id",
  emailField: "invitee_email",
  nameField: "invitee_name",
};

export const PASSLINE_SCHEMA: SourceSchema = {
  source: "passline",
  label: "PassLine Attendance",
  fields: [
    {
      key: "passline_id",
      label: "Ticket ID",
      type: "text",
      required: true,
      aliases: [
        "ticket id",
        "ticket_id",
        "id",
        "pass id",
        "pass_id",
        "barcode",
        "entry id",
        "check-in id",
        "checkin id",
      ],
      description: "PassLine ticket or entry ID",
    },
    {
      key: "attendee_email",
      label: "Attendee Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "attendee email",
        "attendee_email",
        "guest email",
        "e-mail",
        "contact email",
      ],
      description: "Attendee email address",
    },
    {
      key: "attendee_name",
      label: "Attendee Name",
      type: "text",
      required: false,
      aliases: [
        "name",
        "full name",
        "full_name",
        "attendee name",
        "attendee_name",
        "guest name",
        "visitor name",
        "first name",
      ],
      description: "Attendee full name",
    },
    {
      key: "event_name",
      label: "Event Name",
      type: "text",
      required: false,
      aliases: [
        "event",
        "event name",
        "event_name",
        "event title",
        "event_title",
        "class",
        "class name",
        "session",
      ],
      description: "Name of the event or class",
    },
    {
      key: "check_in_time",
      label: "Check-in Time",
      type: "timestamp",
      required: true,
      aliases: [
        "checked in at",
        "checked_in_at",
        "check-in time",
        "check_in_time",
        "checkin time",
        "check in",
        "scan time",
        "entry time",
        "arrival time",
        "timestamp",
        "date",
      ],
      description: "When the attendee checked in",
    },
  ],
  idField: "passline_id",
  emailField: "attendee_email",
  nameField: "attendee_name",
};

export const SCHEMAS: Record<string, SourceSchema> = {
  stripe: STRIPE_SCHEMA,
  calendly: CALENDLY_SCHEMA,
  passline: PASSLINE_SCHEMA,
};

export function getSchema(source: string): SourceSchema | undefined {
  return SCHEMAS[source];
}
