import type { SourceSchema, SchemaKey } from "@/lib/types";

export const STRIPE_SCHEMA: SourceSchema = {
  source: "stripe",
  label: "Stripe Payments",
  fields: [
    {
      key: "external_payment_id",
      label: "Payment ID",
      type: "text",
      required: true,
      aliases: [
        "stripe_payment_id",
        "id",
        "payment_id",
        "charge_id",
        "payment id",
        "charge id",
        "stripe id",
        "transaction id",
        "transaction_id",
      ],
      samplePattern: /^(pi_|ch_|in_)/,
      description: "Stripe payment or charge ID (e.g. pi_xxx, ch_xxx)",
    },
    {
      key: "customer_email",
      label: "Customer Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "customer email",
        "customer_email",
        "receipt email",
        "receipt_email",
        "billing email",
      ],
      description: "Customer email address",
    },
    {
      key: "customer_name",
      label: "Customer Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "name",
        "customer name",
        "customer_name",
        "billing name",
        "billing_name",
        "cardholder name",
      ],
      description: "Customer full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Customer phone number",
    },
    {
      key: "amount",
      label: "Amount",
      type: "currency",
      required: true,
      aliases: [
        "amount",
        "total",
        "charge amount",
        "payment amount",
        "amount (usd)",
        "converted amount",
      ],
      description: "Payment amount (numeric, may include $ or commas)",
    },
    {
      key: "currency",
      label: "Currency",
      type: "text",
      required: false,
      aliases: [
        "currency",
        "currency code",
        "payment currency",
        "converted currency",
      ],
      description: "ISO currency code (e.g. USD, EUR)",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: ["status", "payment status", "charge status", "outcome"],
      enumValues: ["succeeded", "pending", "failed", "refunded"],
      description: "Payment status",
    },
    {
      key: "customer_external_id",
      label: "Customer ID",
      type: "text",
      required: false,
      aliases: [
        "stripe_customer_id",
        "customer_id",
        "customer id",
        "cus_id",
        "stripe customer id",
      ],
      samplePattern: /^cus_/,
      description: "Stripe customer ID (e.g. cus_xxx)",
    },
    {
      key: "payment_date",
      label: "Payment Date",
      type: "timestamp",
      required: true,
      aliases: [
        "created",
        "created (utc)",
        "date",
        "payment date",
        "payment_date",
        "created_at",
        "created at",
        "timestamp",
        "paid at",
        "charge date",
      ],
      description: "When the payment was created",
    },
  ],
  idField: "external_payment_id",
  emailField: "customer_email",
  nameField: "customer_name",
  phoneField: "phone",
  customerIdField: "customer_external_id",
};

export const CALENDLY_SCHEMA: SourceSchema = {
  source: "calendly",
  label: "Calendly Bookings",
  fields: [
    {
      key: "external_booking_id",
      label: "Event ID",
      type: "text",
      required: true,
      aliases: [
        "calendly_event_id",
        "event uri",
        "event_uri",
        "event id",
        "event_id",
        "uri",
        "calendly id",
        "booking id",
        "invitee uri",
      ],
      description: "Calendly event URI or ID",
    },
    {
      key: "invitee_id",
      label: "Invitee ID",
      type: "text",
      required: false,
      aliases: [
        "calendly_invitee_id",
        "invitee_id",
        "invitee id",
      ],
      description: "Calendly invitee ID",
    },
    {
      key: "invitee_email",
      label: "Invitee Email",
      type: "email",
      required: false,
      aliases: [
        "invitee email",
        "invitee_email",
        "email",
        "guest email",
        "attendee email",
        "invitee e-mail",
      ],
      description: "Invitee email address",
    },
    {
      key: "invitee_name",
      label: "Invitee Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "invitee name",
        "invitee_name",
        "name",
        "guest name",
        "attendee name",
        "invitee full name",
      ],
      description: "Invitee full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Invitee phone number",
    },
    {
      key: "event_type",
      label: "Event Type",
      type: "text",
      required: false,
      aliases: [
        "service_name",
        "event type",
        "event_type",
        "event type name",
        "meeting type",
        "type",
        "appointment type",
      ],
      description: "Type of meeting/event",
    },
    {
      key: "start_time",
      label: "Start Time",
      type: "timestamp",
      required: true,
      aliases: [
        "booking_date",
        "start date & time",
        "start date and time",
        "start_time",
        "start time",
        "scheduled time",
        "start",
        "event date",
        "date",
        "meeting start",
      ],
      description: "Scheduled start time",
    },
    {
      key: "end_time",
      label: "End Time",
      type: "timestamp",
      required: false,
      aliases: [
        "end date & time",
        "end date and time",
        "end_time",
        "end time",
        "end",
        "meeting end",
      ],
      description: "Scheduled end time",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: [
        "status",
        "event status",
        "booking status",
        "canceled",
        "cancelled",
      ],
      enumValues: ["scheduled", "completed", "cancelled", "no_show", "confirmed", "rescheduled"],
      description: "Booking status",
    },
  ],
  idField: "external_booking_id",
  emailField: "invitee_email",
  nameField: "invitee_name",
  phoneField: "phone",
};

export const PASSLINE_SCHEMA: SourceSchema = {
  source: "passline",
  label: "PassLine Attendance",
  fields: [
    {
      key: "external_attendance_id",
      label: "Ticket ID",
      type: "text",
      required: true,
      aliases: [
        "passline_id",
        "ticket id",
        "ticket_id",
        "id",
        "pass id",
        "pass_id",
        "barcode",
        "entry id",
        "check-in id",
        "checkin id",
      ],
      description: "PassLine ticket or entry ID",
    },
    {
      key: "attendee_email",
      label: "Attendee Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "attendee email",
        "attendee_email",
        "guest email",
        "e-mail",
        "contact email",
      ],
      description: "Attendee email address",
    },
    {
      key: "attendee_name",
      label: "Attendee Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "name",
        "full name",
        "attendee name",
        "attendee_name",
        "guest name",
        "visitor name",
        "first name",
      ],
      description: "Attendee full name",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile"],
      description: "Attendee phone number",
    },
    {
      key: "event_name",
      label: "Event Name",
      type: "text",
      required: false,
      aliases: [
        "event",
        "event name",
        "event_name",
        "event title",
        "event_title",
        "class",
        "class name",
        "session",
      ],
      description: "Name of the event or class",
    },
    {
      key: "check_in_time",
      label: "Check-in Time",
      type: "timestamp",
      required: true,
      aliases: [
        "check_in_date",
        "checked in at",
        "checked_in_at",
        "check-in time",
        "check_in_time",
        "checkin time",
        "check in",
        "scan time",
        "entry time",
        "arrival time",
        "timestamp",
        "date",
      ],
      description: "When the attendee checked in",
    },
    {
      key: "ticket_type",
      label: "Ticket Type",
      type: "text",
      required: false,
      aliases: [
        "ticket_type",
        "ticket type",
        "pass type",
        "pass_type",
        "entry type",
      ],
      description: "Type of ticket or pass",
    },
  ],
  idField: "external_attendance_id",
  emailField: "attendee_email",
  nameField: "attendee_name",
  phoneField: "phone",
};

export const POS_SCHEMA: SourceSchema = {
  source: "pos",
  label: "POS Transactions",
  fields: [
    {
      key: "external_payment_id",
      label: "Transaction ID",
      type: "text",
      required: true,
      aliases: [
        "pos_transaction_id",
        "transaction_id",
        "transaction id",
        "receipt id",
        "receipt_id",
      ],
      description: "POS transaction ID",
    },
    {
      key: "membership_id",
      label: "Membership ID",
      type: "text",
      required: false,
      aliases: [
        "membership_id",
        "membership id",
        "member_id",
        "member id",
        "customer_id",
      ],
      description: "Customer membership or loyalty ID",
    },
    {
      key: "customer_email",
      label: "Email",
      type: "email",
      required: false,
      aliases: [
        "member_email",
        "email",
        "customer_email",
        "customer email",
      ],
      description: "Customer email address",
    },
    {
      key: "customer_phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: [
        "member_phone",
        "phone",
        "customer_phone",
        "customer phone",
        "mobile",
      ],
      description: "Customer phone number",
    },
    {
      key: "location",
      label: "Location",
      type: "text",
      required: false,
      aliases: [
        "location",
        "store",
        "store_name",
        "store name",
        "branch",
      ],
      description: "Store or location name",
    },
    {
      key: "payment_type",
      label: "Payment Type",
      type: "text",
      required: false,
      aliases: [
        "transaction_type",
        "transaction type",
        "payment_type",
        "payment type",
        "method",
        "payment_method",
      ],
      description: "Type of transaction (e.g. credit, debit, cash)",
    },
    {
      key: "amount",
      label: "Amount",
      type: "currency",
      required: true,
      aliases: [
        "amount",
        "total",
        "transaction_amount",
        "transaction amount",
        "sale amount",
      ],
      description: "Transaction amount",
    },
    {
      key: "currency",
      label: "Currency",
      type: "text",
      required: false,
      aliases: [
        "currency",
        "currency_code",
        "currency code",
      ],
      description: "ISO currency code",
    },
    {
      key: "payment_date",
      label: "Transaction Date",
      type: "timestamp",
      required: true,
      aliases: [
        "transaction_date",
        "transaction date",
        "date",
        "payment_date",
        "payment date",
        "sale date",
        "sale_date",
      ],
      description: "When the transaction occurred",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: ["status", "transaction_status", "transaction status"],
      enumValues: ["approved", "succeeded", "pending", "failed", "refunded", "void"],
      description: "Transaction status",
    },
  ],
  idField: "external_payment_id",
  emailField: "customer_email",
  nameField: "",
  customerIdField: "membership_id",
  phoneField: "customer_phone",
};

export const WETRAVEL_SCHEMA: SourceSchema = {
  source: "wetravel",
  label: "WeTravel Bookings",
  fields: [
    {
      key: "external_booking_id",
      label: "Booking ID",
      type: "text",
      required: true,
      aliases: [
        "booking_id",
        "booking id",
        "reservation_id",
        "reservation id",
      ],
      description: "WeTravel booking ID",
    },
    {
      key: "participant_name",
      label: "Participant Name",
      type: "text",
      required: false,
      aliases: [
        "participant_name",
        "participant name",
        "name",
        "full_name",
        "full name",
        "traveler name",
        "traveler_name",
      ],
      description: "Participant full name",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "participant_email",
        "participant email",
        "contact_email",
      ],
      description: "Participant email address",
    },
    {
      key: "country",
      label: "Country",
      type: "text",
      required: false,
      aliases: [
        "country",
        "nationality",
        "country_code",
        "country code",
      ],
      description: "Participant country",
    },
    {
      key: "trip_name",
      label: "Trip Name",
      type: "text",
      required: false,
      aliases: [
        "trip_name",
        "trip name",
        "tour name",
        "tour_name",
        "event",
        "experience",
      ],
      description: "Name of the trip or tour",
    },
    {
      key: "total_trip_price",
      label: "Total Trip Price",
      type: "currency",
      required: false,
      aliases: [
        "total_trip_price",
        "total trip price",
        "trip_price",
        "trip price",
        "total_price",
        "total price",
      ],
      description: "Total price for the trip",
    },
    {
      key: "amount_paid",
      label: "Amount Paid",
      type: "currency",
      required: false,
      aliases: [
        "amount_paid",
        "amount paid",
        "paid",
        "amount",
        "payment_amount",
      ],
      description: "Amount paid so far",
    },
    {
      key: "remaining_balance",
      label: "Remaining Balance",
      type: "currency",
      required: false,
      aliases: [
        "remaining_balance",
        "remaining balance",
        "balance",
        "balance_due",
        "balance due",
      ],
      description: "Remaining balance to be paid",
    },
    {
      key: "payment_plan_type",
      label: "Payment Plan Type",
      type: "text",
      required: false,
      aliases: [
        "payment_plan_type",
        "payment plan type",
        "payment_plan",
        "payment plan",
        "plan_type",
      ],
      description: "Type of payment plan",
    },
    {
      key: "booking_date",
      label: "Booking Date",
      type: "timestamp",
      required: true,
      aliases: [
        "booking_date",
        "booking date",
        "booked_at",
        "booked at",
        "date",
        "reservation_date",
      ],
      description: "When the booking was made",
    },
    {
      key: "trip_start_date",
      label: "Trip Start Date",
      type: "date",
      required: false,
      aliases: [
        "trip_start_date",
        "trip start date",
        "start_date",
        "start date",
        "departure_date",
        "departure date",
      ],
      description: "Trip start date",
    },
    {
      key: "trip_end_date",
      label: "Trip End Date",
      type: "date",
      required: false,
      aliases: [
        "trip_end_date",
        "trip end date",
        "end_date",
        "end date",
        "return_date",
        "return date",
      ],
      description: "Trip end date",
    },
    {
      key: "status",
      label: "Status",
      type: "enum",
      required: false,
      aliases: [
        "status",
        "booking_status",
        "booking status",
      ],
      enumValues: ["confirmed", "cancelled", "pending", "completed"],
      description: "Booking status",
    },
    {
      key: "refund_amount",
      label: "Refund Amount",
      type: "currency",
      required: false,
      aliases: [
        "refund_amount",
        "refund amount",
        "refund",
        "refunded_amount",
      ],
      description: "Amount refunded",
    },
    {
      key: "lead_source_channel",
      label: "Lead Source Channel",
      type: "text",
      required: false,
      aliases: ["lead_source_channel", "lead source channel", "source_channel", "channel"],
      description: "Marketing channel source",
    },
    {
      key: "utm_source",
      label: "UTM Source",
      type: "text",
      required: false,
      aliases: ["utm_source", "utm source"],
      description: "UTM source parameter",
    },
    {
      key: "utm_medium",
      label: "UTM Medium",
      type: "text",
      required: false,
      aliases: ["utm_medium", "utm medium"],
      description: "UTM medium parameter",
    },
    {
      key: "utm_campaign",
      label: "UTM Campaign",
      type: "text",
      required: false,
      aliases: ["utm_campaign", "utm campaign"],
      description: "UTM campaign parameter",
    },
    {
      key: "utm_content",
      label: "UTM Content",
      type: "text",
      required: false,
      aliases: ["utm_content", "utm content"],
      description: "UTM content parameter",
    },
    {
      key: "referrer",
      label: "Referrer",
      type: "text",
      required: false,
      aliases: ["referrer", "referral_url", "referral url", "referred_by"],
      description: "Referrer URL or source",
    },
    {
      key: "referral_partner",
      label: "Referral Partner",
      type: "text",
      required: false,
      aliases: ["referral_partner", "referral partner", "partner", "affiliate"],
      description: "Referral partner name",
    },
    {
      key: "lead_capture_method",
      label: "Lead Capture Method",
      type: "text",
      required: false,
      aliases: ["lead_capture_method", "lead capture method", "capture_method"],
      description: "How the lead was captured",
    },
  ],
  idField: "external_booking_id",
  emailField: "email",
  nameField: "participant_name",
};

export const CRM_SCHEMA: SourceSchema = {
  source: "crm",
  label: "CRM / Members",
  fields: [
    {
      key: "member_id",
      label: "Member ID",
      type: "text",
      required: false,
      aliases: [
        "member_id",
        "member id",
        "membership_id",
        "membership id",
        "customer_id",
        "customer id",
        "client_id",
        "client id",
      ],
      description: "Membership or client ID",
    },
    {
      key: "full_name",
      label: "Full Name",
      type: "text",
      required: false,
      aliases: [
        "full_name",
        "full name",
        "name",
        "client_name",
        "client name",
        "member_name",
        "member name",
      ],
      description: "Customer full name",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: false,
      aliases: [
        "email",
        "e-mail",
        "email_address",
        "email address",
        "contact_email",
        "contact email",
      ],
      description: "Customer email address",
    },
    {
      key: "phone",
      label: "Phone",
      type: "text",
      required: false,
      aliases: ["phone", "phone_number", "telephone", "mobile", "cell"],
      description: "Customer phone number",
    },
    {
      key: "last_visit_date",
      label: "Last Visit Date",
      type: "date",
      required: false,
      aliases: [
        "last_visit_date",
        "last visit date",
        "last_visit",
        "last visit",
        "last_check_in",
        "last check-in",
        "last_attended",
      ],
      description: "Date of last visit or check-in",
    },
    {
      key: "classes_remaining",
      label: "Classes Remaining",
      type: "text",
      required: false,
      aliases: [
        "classes_remaining",
        "classes remaining",
        "remaining_classes",
        "remaining classes",
        "credits",
        "sessions_remaining",
        "sessions remaining",
      ],
      description: "Number of classes or sessions remaining",
    },
    {
      key: "membership_status",
      label: "Membership Status",
      type: "text",
      required: false,
      aliases: [
        "membership_status",
        "membership status",
        "status",
        "member_status",
        "member status",
        "account_status",
        "account status",
      ],
      description: "Current membership status (active, expired, etc.)",
    },
    {
      key: "referral_source",
      label: "Referral Source",
      type: "text",
      required: false,
      aliases: [
        "referral_source",
        "referral source",
        "how_did_you_hear",
        "how did you hear",
        "source",
        "lead_source",
        "lead source",
      ],
      description: "How the customer found you",
    },
    {
      key: "notes",
      label: "Notes",
      type: "text",
      required: false,
      aliases: ["notes", "note", "comments", "comment"],
      description: "Additional notes about the customer",
    },
    {
      key: "country",
      label: "Country",
      type: "text",
      required: false,
      aliases: ["country", "nationality", "country_code", "country code"],
      description: "Customer country or nationality",
    },
    {
      key: "occupation",
      label: "Occupation",
      type: "text",
      required: false,
      aliases: ["occupation", "job", "profession", "job_title", "job title"],
      description: "Customer occupation or profession",
    },
    {
      key: "skill_level",
      label: "Skill Level",
      type: "text",
      required: false,
      aliases: ["skill_level", "level", "experience_level", "experience level", "ability"],
      description: "Customer skill or experience level",
    },
    {
      key: "member_type",
      label: "Member Type",
      type: "text",
      required: false,
      aliases: ["member_type", "membership_type", "membership type", "type", "plan", "tier"],
      description: "Membership type or plan tier",
    },
    {
      key: "join_date",
      label: "Join Date",
      type: "date",
      required: false,
      aliases: ["join_date", "joined", "signup_date", "signup date", "enrollment_date", "enrollment date"],
      description: "Date the customer joined or signed up",
    },
    {
      key: "preferred_currency",
      label: "Preferred Currency",
      type: "text",
      required: false,
      aliases: ["preferred_currency", "currency_preference", "currency preference"],
      description: "Customer's preferred currency",
    },
    {
      key: "preferred_time_slot",
      label: "Preferred Time Slot",
      type: "text",
      required: false,
      aliases: ["preferred_time_slot", "time_slot", "time slot", "preferred_time", "preferred time"],
      description: "Customer's preferred time slot for classes/sessions",
    },
  ],
  idField: "member_id",
  emailField: "email",
  nameField: "full_name",
  phoneField: "phone",
};

export const ATTRIBUTION_FIRSTTOUCH_SCHEMA: SourceSchema = {
  source: "attribution",
  label: "Attribution (First Touch)",
  fields: [
    {
      key: "conversion_id",
      label: "Conversion ID",
      type: "text",
      required: true,
      aliases: ["conversion_id", "conversion id"],
      description: "Unique conversion identifier",
    },
    {
      key: "conversion_source",
      label: "Conversion Source",
      type: "text",
      required: false,
      aliases: ["conversion_source", "conversion source"],
      description: "Source of the conversion",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: false,
      aliases: ["email", "e-mail", "email_address", "email address"],
      description: "Customer email address",
    },
    {
      key: "full_name",
      label: "Full Name",
      type: "text",
      required: false,
      aliases: ["full_name", "full name", "name"],
      description: "Customer full name",
    },
    {
      key: "product",
      label: "Product",
      type: "text",
      required: false,
      aliases: ["product", "product_name", "product name"],
      description: "Product purchased",
    },
    {
      key: "revenue_usd",
      label: "Revenue (USD)",
      type: "currency",
      required: false,
      aliases: ["revenue_usd", "revenue", "revenue usd", "amount"],
      description: "Revenue in USD",
    },
    {
      key: "conversion_date",
      label: "Conversion Date",
      type: "date",
      required: false,
      aliases: ["conversion_date", "conversion date", "date"],
      description: "Date of conversion",
    },
    {
      key: "n_touchpoints",
      label: "Touchpoints",
      type: "text",
      required: false,
      aliases: ["n_touchpoints", "touchpoints", "num_touchpoints"],
      description: "Number of touchpoints in the journey",
    },
    {
      key: "journey_span_days",
      label: "Journey Span (Days)",
      type: "text",
      required: false,
      aliases: ["journey_span_days", "journey span days", "journey_days"],
      description: "Days from first touch to conversion",
    },
    {
      key: "first_touch_channel",
      label: "First Touch Channel",
      type: "text",
      required: false,
      aliases: ["first_touch_channel", "first touch channel"],
      description: "First marketing channel touch",
    },
    {
      key: "first_touch_utm_source",
      label: "First Touch UTM Source",
      type: "text",
      required: false,
      aliases: ["first_touch_utm_source", "first touch utm source"],
      description: "UTM source of first touch",
    },
    {
      key: "first_touch_utm_medium",
      label: "First Touch UTM Medium",
      type: "text",
      required: false,
      aliases: ["first_touch_utm_medium", "first touch utm medium"],
      description: "UTM medium of first touch",
    },
    {
      key: "first_touch_campaign",
      label: "First Touch Campaign",
      type: "text",
      required: false,
      aliases: ["first_touch_campaign", "first touch campaign"],
      description: "Campaign of first touch",
    },
    {
      key: "first_touch_referrer",
      label: "First Touch Referrer",
      type: "text",
      required: false,
      aliases: ["first_touch_referrer", "first touch referrer"],
      description: "Referrer of first touch",
    },
    {
      key: "first_touch_date",
      label: "First Touch Date",
      type: "date",
      required: false,
      aliases: ["first_touch_date", "first touch date"],
      description: "Date of first touch",
    },
    {
      key: "last_touch_channel",
      label: "Last Touch Channel",
      type: "text",
      required: false,
      aliases: ["last_touch_channel", "last touch channel"],
      description: "Last marketing channel touch",
    },
    {
      key: "last_touch_utm_source",
      label: "Last Touch UTM Source",
      type: "text",
      required: false,
      aliases: ["last_touch_utm_source", "last touch utm source"],
      description: "UTM source of last touch",
    },
    {
      key: "last_touch_date",
      label: "Last Touch Date",
      type: "date",
      required: false,
      aliases: ["last_touch_date", "last touch date"],
      description: "Date of last touch",
    },
    {
      key: "attributed_revenue_usd",
      label: "Attributed Revenue (USD)",
      type: "currency",
      required: false,
      aliases: ["attributed_revenue_usd", "attributed revenue usd", "attributed_revenue"],
      description: "Revenue attributed to first touch",
    },
  ],
  idField: "conversion_id",
  emailField: "email",
  nameField: "full_name",
};

export const ATTRIBUTION_JOURNEYS_SCHEMA: SourceSchema = {
  source: "attribution",
  label: "Attribution (Journeys)",
  fields: [
    {
      key: "touch_id",
      label: "Touch ID",
      type: "text",
      required: true,
      aliases: ["touch_id", "touch id"],
      description: "Unique touchpoint identifier",
    },
    {
      key: "conversion_id",
      label: "Conversion ID",
      type: "text",
      required: false,
      aliases: ["conversion_id", "conversion id"],
      description: "Conversion this touchpoint belongs to",
    },
    {
      key: "conversion_source",
      label: "Conversion Source",
      type: "text",
      required: false,
      aliases: ["conversion_source", "conversion source"],
      description: "Source of the conversion",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: false,
      aliases: ["email", "e-mail", "email_address", "email address"],
      description: "Customer email address",
    },
    {
      key: "full_name",
      label: "Full Name",
      type: "text",
      required: false,
      aliases: ["full_name", "full name", "name"],
      description: "Customer full name",
    },
    {
      key: "product",
      label: "Product",
      type: "text",
      required: false,
      aliases: ["product", "product_name", "product name"],
      description: "Product purchased",
    },
    {
      key: "revenue_usd",
      label: "Revenue (USD)",
      type: "currency",
      required: false,
      aliases: ["revenue_usd", "revenue", "revenue usd"],
      description: "Revenue in USD",
    },
    {
      key: "conversion_date",
      label: "Conversion Date",
      type: "date",
      required: false,
      aliases: ["conversion_date", "conversion date"],
      description: "Date of conversion",
    },
    {
      key: "touch_number",
      label: "Touch Number",
      type: "text",
      required: false,
      aliases: ["touch_number", "touch number"],
      description: "Order of this touch in the journey",
    },
    {
      key: "total_touches",
      label: "Total Touches",
      type: "text",
      required: false,
      aliases: ["total_touches", "total touches"],
      description: "Total touchpoints in the journey",
    },
    {
      key: "touch_position",
      label: "Touch Position",
      type: "text",
      required: false,
      aliases: ["touch_position", "touch position", "position"],
      description: "Position label (first, middle, last)",
    },
    {
      key: "channel",
      label: "Channel",
      type: "text",
      required: false,
      aliases: ["channel", "touch_channel"],
      description: "Marketing channel of this touchpoint",
    },
    {
      key: "utm_source",
      label: "UTM Source",
      type: "text",
      required: false,
      aliases: ["utm_source", "utm source"],
      description: "UTM source parameter",
    },
    {
      key: "utm_medium",
      label: "UTM Medium",
      type: "text",
      required: false,
      aliases: ["utm_medium", "utm medium"],
      description: "UTM medium parameter",
    },
    {
      key: "utm_campaign",
      label: "UTM Campaign",
      type: "text",
      required: false,
      aliases: ["utm_campaign", "utm campaign"],
      description: "UTM campaign parameter",
    },
    {
      key: "referrer",
      label: "Referrer",
      type: "text",
      required: false,
      aliases: ["referrer", "referral_url"],
      description: "Referrer URL",
    },
    {
      key: "touch_date",
      label: "Touch Date",
      type: "date",
      required: false,
      aliases: ["touch_date", "touch date"],
      description: "Date of this touchpoint",
    },
    {
      key: "days_before_conversion",
      label: "Days Before Conversion",
      type: "text",
      required: false,
      aliases: ["days_before_conversion", "days before conversion"],
      description: "Days between this touch and conversion",
    },
    {
      key: "first_touch_credit",
      label: "First Touch Credit",
      type: "currency",
      required: false,
      aliases: ["first_touch_credit", "first touch credit"],
      description: "Credit allocated under first-touch model",
    },
    {
      key: "first_touch_revenue",
      label: "First Touch Revenue",
      type: "currency",
      required: false,
      aliases: ["first_touch_revenue", "first touch revenue"],
      description: "Revenue allocated under first-touch model",
    },
  ],
  idField: "touch_id",
  emailField: "email",
  nameField: "full_name",
};

// Keep backward compat: 'attribution' points to firsttouch
export const ATTRIBUTION_SCHEMA = ATTRIBUTION_FIRSTTOUCH_SCHEMA;

export const SCHEMAS: Record<string, SourceSchema> = {
  stripe: STRIPE_SCHEMA,
  calendly: CALENDLY_SCHEMA,
  passline: PASSLINE_SCHEMA,
  pos: POS_SCHEMA,
  wetravel: WETRAVEL_SCHEMA,
  crm: CRM_SCHEMA,
  attribution: ATTRIBUTION_FIRSTTOUCH_SCHEMA,
  attribution_firsttouch: ATTRIBUTION_FIRSTTOUCH_SCHEMA,
  attribution_journeys: ATTRIBUTION_JOURNEYS_SCHEMA,
};

export function getSchema(source: string): SourceSchema | undefined {
  return SCHEMAS[source];
}

/** Resolve a SchemaKey to the DB-safe SourceType. */
export function schemaKeyToSourceType(key: string): string {
  if (key.startsWith("attribution")) return "attribution";
  return key;
}

/** Detect attribution sub-type from CSV headers. */
export function detectAttributionSubtype(headers: string[]): SchemaKey {
  const lowerHeaders = new Set(headers.map((h) => h.toLowerCase().trim()));
  // Journeys-specific columns
  if (lowerHeaders.has("touch_id") || lowerHeaders.has("touch_number") || lowerHeaders.has("touch_position")) {
    return "attribution_journeys";
  }
  return "attribution_firsttouch";
}
